// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cldtbkwhjksqckezdzzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZHRia3doamtzcWNrZXpkenpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MjIzOTMsImV4cCI6MjA3MjE5ODM5M30.tx7qH98oLatOfodhvAHq38nJV2EKP2XFZXWoLkHUfBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});